name: My Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Check Logs
        uses: SyedSibtainRazvi/check_logs@main
